# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: build-macOS-M1

jobs:
  build-bin-macOS-M1:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macosArm64,              r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: any::rcmdcheck, any::XML
          needs: check
          # See https://github.com/r-lib/actions/issues/559 for the XML issue

      - name: Build
        run: |
          install.packages("pkgbuild")
          pkgbuild::build(".", binary = TRUE)
        shell: Rscript {0}
      
      - uses: actions/upload-artifact@v3
        with:
          name: binaries-for-mac-M1
          path: /Users/runner/work/ade4/ade4_*.tgz
          